name: foodkie_express
description: A single-user food management app for efficient menu handling and order processing.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.0

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Firebase Services
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_remote_config: ^5.0.2

  # Authentication
  pinput: ^3.0.1

  # Local Storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  dio: ^5.3.2
  connectivity_plus: ^4.0.2

  # Utilities
  intl: ^0.19.0
  uuid: ^3.0.7
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  permission_handler: ^11.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_bluetooth_serial: ^0.4.0
  network_info_plus: ^4.0.2

  # Data Handling
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  firebase_app_check: ^0.3.2+4
  http:

  # Animations
  flutter_animate: ^4.2.0

  # Form Handling
  form_validator: ^2.1.1
  image_cropper: ^9.0.0

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.3

  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2

  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4

  # Icons & Assets - Modified version for compatibility
  flutter_native_splash: ^2.3.2

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android: true
  ios: true


# Flutter App Icon Configuration

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700